<?xml version="1.0"?>
<package format="2">
  <name>super_odometry</name>
  <version>0.0.0</version>

  <description>
    This is an implementation of super_odometry, which is based on LOAM algorithm.
    LOAM is described in the following paper:
    J. Zhang and S. Singh. LOAM: Lidar Odometry and Mapping in Real-time.
      Robotics: Science and Systems Conference (RSS). Berkeley, CA, July 2014.
  </description>

  <maintainer email="shibowing@gmail.com">Shibo Zhao</maintainer>

  <license>BSD</license>
 
  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>tf</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>std_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>image_transport</depend>
  <depend>cv_bridge</depend>
  <depend>pcl_ros</depend>
  <depend>pcl_conversions</depend>
  <depend>sophus</depend>
  <depend>livox_ros_driver</depend>
  <depend>super_odometry_msgs</depend>

  <build_depend>eigen</build_depend>
  <build_depend>ceres</build_depend>
  <build_depend>gtsam</build_depend>
  <build_depend>tbb</build_depend>

  <exec_depend>eigen</exec_depend>
  <exec_depend>ceres</exec_depend>
  <exec_depend>gtsam</exec_depend>
  <exec_depend>tbb</exec_depend>

  <export>
    <cpp cflags="-std=c++17"/>
  </export>
</package>
